/obj/item/drinkable_bloodpack
/obj/item/drinkable_bloodpack/elite
/obj/item/ammo_box/vampire/c9mm
/obj/item/ammo_box/vampire/c44
/obj/item/ammo_box/vampire/c556
/obj/item/ammo_box/vampire/c12g
/obj/item/ammo_box/vampire/c556/incendiary
/obj/item/ammo_box/vampire/arrows
/obj/item/melee/vampirearms/stake
/obj/item/melee/vampirearms/fireaxe
/obj/item/melee/vampirearms/katana
/obj/item/melee/vampirearms/baseball
/obj/item/melee/vampirearms/tire
/obj/item/melee/vampirearms/knife
/obj/item/melee/vampirearms/chainsaw
/obj/item/melee/vampirearms/shovel
/obj/item/gun/ballistic/vampire/revolver
/obj/item/gun/ballistic/automatic/vampire/deagle
/obj/item/gun/ballistic/automatic/vampire/uzi
/obj/item/gun/ballistic/automatic/vampire/ar15
/obj/item/gun/ballistic/automatic/vampire/sniper
/obj/item/gun/ballistic/shotgun/vampire
/obj/item/gun/ballistic/shotgun/toy/crossbow/vampire