#define COMSIG_VAMP_DRINKBLOOD "vamp_drinkblood"
#define COMSIG_VAMP_CURSE_NOSFERATU "vamp_curse_nosferatu"
#define COMSIG_VAMP_CURSE_MALKAVIAN "vamp_cuse_malkavian"
#define COMSIG_VAMP_SEENBYPEOPLE "vamp_seenbypeople"
#define COMSIG_VAMP_WASTEBLOOD "vamp_wasteblood"
